// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class BankAccount
{
    public int BankAccountId { get; set; }

    public int AccountId { get; set; }

    public string AccountNumber { get; set; }

    public string AccountName { get; set; }

    public string BankName { get; set; }

    public virtual Account Account { get; set; }
}