// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class BlindBoxImage
{
    public int BlindBoxImageId { get; set; }

    public int BlindBoxId { get; set; }

    public string ImageUrl { get; set; }

    public virtual BlindBox BlindBox { get; set; }
}