// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class CartDetail
{
    public int CartDetailId { get; set; }

    public int CartId { get; set; }

    public int? BlindBoxId { get; set; }

    public int? PackageId { get; set; }

    public int Quantity { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual BlindBox BlindBox { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual Package Package { get; set; }
}