// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class PackageImage
{
    public int PackageImageId { get; set; }

    public int PackageId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Package Package { get; set; }
}