// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int ProductId { get; set; }

    public int OrderId { get; set; }

    public int OrderDetailId { get; set; }

    public int AccountId { get; set; }

    public string Description { get; set; }

    public int Rating { get; set; }

    public DateTime CreateAt { get; set; }

    public string ImageUrl { get; set; }

    public string ReviewStatus { get; set; }

    public virtual Account Account { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }
}