// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Voucher
{
    public int VoucherId { get; set; }

    public int OrderId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public decimal DiscountValue { get; set; }

    public decimal? Money { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual Order Order { get; set; }
}