// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class WalletTransaction
{
    public int TransactionId { get; set; }

    public int WalletId { get; set; }

    public int? OrderId { get; set; }

    public string Status { get; set; }

    public decimal Amount { get; set; }

    public DateTime CreatedAt { get; set; }

    public decimal Balance { get; set; }

    public string TransactionType { get; set; }

    public virtual Order Order { get; set; }

    public virtual Wallet Wallet { get; set; }
}